logo_title: yz1311

style: white

favicon: /favicon.ico

menu:
  作品: /project
  域名: /domain
  友联: /links
  关于: /about
  Github: https://github.com/yz1311

# 做了域名限制，请改成自己的 KEY
valine:
  appId: bjcHY0Y3LeXHz2Ka3Is1zOI2-gzGzoHsz
  appKey: ECMAbUzyDQArdsS8DrjAMOQz

highlight:
  enable: false